### ISSUE TITLE
Custom script not working

### ISSUE THREAD

**Issue by Jerry-Master** [princeton-vl/SEA-RAFT#17]
When following the instructions in your README this error occurs. My platform is Windows.

```
Traceback (most recent call last):
  File "C:\Users\joseperezcano\Desktop\Project5\mvga\stereo_vision\SEA-RAFT\custom.py", line 141, in <module>
    main()
  File "C:\Users\joseperezcano\Desktop\Project5\mvga\stereo_vision\SEA-RAFT\custom.py", line 130, in main
    model = RAFT.from_pretrained(args.url, args=args)
  File "C:\Users\joseperezcano\miniconda3\envs\SEA-RAFT\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\joseperezcano\miniconda3\envs\SEA-RAFT\lib\site-packages\huggingface_hub\hub_mixin.py", line 570, in from_pretrained
    instance = cls._from_pretrained(
  File "C:\Users\joseperezcano\miniconda3\envs\SEA-RAFT\lib\site-packages\huggingface_hub\hub_mixin.py", line 808, in _from_pretrained
    return cls._load_as_safetensor(model, model_file, map_location, strict)
  File "C:\Users\joseperezcano\miniconda3\envs\SEA-RAFT\lib\site-packages\huggingface_hub\hub_mixin.py", line 832, in _load_as_safetensor
    if packaging.version.parse(safetensors.__version__) < packaging.version.parse("0.4.3"):  # type: ignore [attr-defined]
NameError: name 'packaging' is not defined
```

**Comment by Jerry-Master** [comment]
Installing safetensors or transformers fixes the issue. However, in Windows the following line is incorrect:

```
os.system(f"mkdir -p {path}")
```

You could use already existing functions that are platform independent:

```
os.makedirs(path, exist_ok=True)
```

**Comment by MemorySlices** [comment]
Thank you Jerry!
